### ISSUE TITLE
Promise 기반 Console 입력 API를 추가한다. 

### ISSUE THREAD

**Issue by woowahan-cron** [woowacourse-projects/javascript-mission-utils#1]
- Promise 기반으로 Console 입력을 받을 수 있는 API 추가를 검토한다.   
  - 지원자가 구현하는 방식에 관계 없이 정상적으로 테스트 코드 실행 및 종료 처리 등이 가능한지 검토한다. 
  - 과제 내 예제 테스트 코드로 제공할 정상 동작 케이스, 예외 케이스를 함께 검토한다.
- 동기 방식 Console 입력 API 추가를 검토한다.

**Comment by woowahan-cron** [comment]
## 반복해서 사용하는 Mock, Spy 코드를 유틸 라이브러리에서 제공 시 이슈

서버에서 채점할 시에도 비슷한 이슈가 생길 것으로 예상됩니다.
```
Jest worker encountered 4 child process exceptions, exceeding retry limit.
```

```
jest --runInBand
```

위의 명령어를 사용해서 실행할 수는 있지만, 옵션을 지정하여 실행하게 되었을 때도 발생할 수 있는 이슈를 고려해 봐야 할 것 같아요.

참고: [Jest worker encountered 4 child process exceptions, exceeding retry limit.](https://www.inflearn.com/questions/979348/11-4-%EA%B0%95%EC%9D%98-jest-worker-encountered-4-child-process-exceptions-exceeding-retry-lim)

**Comment by woowahan-cron** [comment]
## 개선 작업 중 발생한 이슈

### 재귀 포함 여러 메서드를 호출하면서 입력받는 경우

#### 현상

아래와 같이 console.log에 누적되는 프로그램을 만든다고 가정했어요
그러면, 정상적인 테스트라면 4개의 검증이 모두 통과되어야 하지만, console을 위한 함수는 2번밖에 안 불렸다고 합니다.ㅠㅠ 무슨 일일까요?
> number of calls: 2


```js
expect(logSpy).toHaveBeenCalledWith("Hello, Susan!");
expect(logSpy).toHaveBeenCalledWith("You are 12 years old.");
expect(logSpy).toHaveBeenCalledWith("Hello, Minsu!");
expect(logSpy).toHaveBeenCalledWith("You are 12 years old.");
``` 

![Image](https://github.com/woowahan-cron/daily-cron/assets/112997662/506f70d2-df62-4f91-8e22-686f40ab14aa)


#### 원인

하나의 함수에서 입력받는 경우에는 모킹이 제대로 됩니다
하지만, 하나의 함수에서 또 다른 함수를 호출하는 경우에는 더 이상 모킹되지 않는 것 같습니다.
어떻게 날아가는지 정확한 경위에 대해서는 파악 중이에요

```
git checkout success/mock-console-log
git checkout fail/mock-console-log
```

```js
async play() {
    const name = await Console.questionAsync("What's your name? ");
    Console.print(`Hello, ${name}!`);

    const age = await Console.questionAsync("How old are you? ");
    Console.print(`You are ${age} years old.`);

    await Console.questionAsync("게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요");

    const name2 = await Console.questionAsync("What's your name? ");
    Console.print(`Hello, ${name2}!`);

    const age2 = await Console.questionAsync("How old are you? ");
    Console.print(`You are ${age2} years old.`);

    // this.retry();
  }

  async retry() {
    const answer = await Console.questionAsync("게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요: ");
    if (answer === "1") {
      await this.play();
      return true;
    }
    if (answer === "2") {
      Console.close();

      return false;
    }
    return null;
  }
```

### 테스트 검증 시 프로그램을 종료시키지 않은 상태에서 입력값을 검증할 경우

Promise가 pending 상태여서 계속 Jest가 기다린다..
숫자 야구의 경우 아래와 같이 247을 입력하지 않고 123만 입력시키는 경우 맞히지 못한 상태에서 계속 프로그램이 돌고 있어서 채점 케이스가 실패

```js
test.only("최초 시작 시 시작 문구 출력", () => {
    run({
      inputs: ["123", /* 정답을 맞혀서 통과시켜야 passed "247", "2"*/],
      outputs: [RULE_MESSAGE],
      randoms: [2, 4, 7],
    });
  });
```

```js
  test.only("볼1", (done) => {
    run({
      inputs: ["216"],
      outputs: ["1볼"],
      randoms: [1, 3, 5],
      done,
    });
  });
```

위의 경우 "1볼"이라는 테스트 목적을 달성하면 프로그램을 종료해야 하는데, 테스트 코드상 중간에 "1볼"이 찍혔는지를 확인하고 도중에 중단할 수 있는 방법이 없는 것 같습니다

**Comment by woowahan-cron** [comment]
기존 mission-frontend 프리코스 저장소에서 진행하기 복잡한 면이 있는 것 같아서 실험실을 따로 만들어 봤습니다.
나중에 참고해주세요!

```
git clone https://github.com/woowahan-cron/precourse-jest-lab.git

git checkout fail/mock-console-log -> 모킹 실패의 경우
git checkout success/mock-console-log -> 모킹을 성공한 경우
```

**Comment by woowapark** [comment]
# 동기 방식 readline 검토 사항
## 검토 내용    
- Node.js 내장 `readline` 패키지는 기본적으로 비동기 방식으로 구현되어 있기 때문에, 이걸 사용해서 동기식 구현은 어려움
- readline이 해주는 일을 동기적으로 비슷하게 구현해둔 `[readline-sync` 라는 별도의 서드파티 라이브러리](https://www.npmjs.com/package/readline-sync)가 있음
    - readline이 아니라 [[TTY](https://nodejs.org/dist/latest-v18.x/docs/api/tty.html)](https://nodejs.org/dist/latest-v18.x/docs/api/tty.html) 라는 다른 내장 API를 사용. 입출력 스트림 자체를 제어하는 방식
    - ESM을 지원하지 않음. only CJS
        - 유틸리티 라이브러리 코드는 ESM 방식을 사용중이라, ESM으로 변환이 필요하다.
    - 마지막 업데이트가 4년 전이고, 2022년 11월에 GitHub Repo는 아카이브 처리됨. 
    - 유사한 기능을 제공해주는 비교할 만한 다른 라이브러리가 없는 상태
    
## 적용해본 방법
- readline-sync 내에서 readline만 해주는 함수를 가져와서 ESM 방식으로 바꿔서 사용 
  - 기본적으로 패키지 자체가 ESM 방식을 제공해주지 않아 바로 사용은 어려움. 어차피 코드를 직접 가지고 와야 하니 readline을 해주는 쪽만 뜯어서 실험삼아 적용 
- 뜯어와서 적용한 코드: [console-sync.js](https://github.com/woowacourse-projects/javascript-mission-utils/blob/feature/add-console-api/src/console-sync.js)

## 검토 결과
- 사용은 가능 (async/await 구문 없이 일반 함수와 동일하게 호출해서 사용)
```js  
const answer = MissionUtils.Console.readLineSync("질문");
```
- 예제 테스트 및 채점 코드에서도 async/await 없이 해당 메서드를 바로 모킹해서 사용 가능  
```js
test("사용자가 입력한 값을 받아올 수 있어야 한다.", () => {
  // given
  const expectedAnswer = "answer";
  MissionUtils.Console.readLineSync = jest.fn().mockReturnValue(expectedAnswer);

  // when
  const answer = MissionUtils.Console.readLineSync("질문");

  // then
  expect(answer).toBe(expectedAnswer);
});
```
- 단, 지원자가 구현한 방식에 따라 스레드가 아예 블로킹되어 멈출 수 있는 위험이 있음. 이 경우 타임아웃도 발생하지 않고 아예 멈출 수 있어 사이드 이펙트 우려가 있다. 
  - 예를 들어, App class를 구현한 App.js 파일 내에서 동작 테스트를 위해 썼던 `new App().play()` 가 있는 경우, 해당 파일을 읽는 순간 입력을 받기 위해 블로킹 되어 멈추기 때문에 이후 테스트 진행이 불가능
  - +) Java, Kotlin과 다르게 JavaScript는 언어 자체가 비동기 모델을 채택. 동기 방식은 위의 문제와 같은 이유로 언어에서 권장하는 방식을 어기는 방식이다.

## 현재 기준 결론
- 동기 방식이 가능하긴 하지만, 구현 코드에 따라 프로그램이 아예 멈출 수 있어 꼭 선택해야 하는 이유가 있는 게 아니라면 오히려 기존 방식보다 검토 대상이 늘어날 수 있어보임
  - 언어 자체적으로도 명시적으로 권장하지 않는 방식이라, 기존 방식 대비 확실히 더 편해지고 안정적으로 운영할 수 있는 방법이 아니라면 채택하기 어려워보임
